1. Create a null vector of size 10 but the fifth value which is 1.

In [2]:
import numpy as np
null_vector=np.zeros(10)
null_vector[4]=1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


2. Create a vector with values ranging from 10 to 49.

In [3]:
import numpy as np
vec=np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


3. Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
import numpy as np
mat=np.arange(0,9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [5]:
import numpy as np
non_zero=np.array([1,2,0,0,4,0])
ind=np.where(non_zero!=0)
print(ind)

(array([0, 1, 4]),)


5. Create a 10x10 array with random values and find the minimum and maximum values.

In [10]:
import numpy as np
x=np.random.random((10,10))
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Minimum and Maximum Values:
0.01359916099077052 0.9859720663751173


6. Create a random vector of size 30 and find the mean value.

In [13]:
import numpy as np
rand_vec=np.random.random(30)
print("Mean value is",rand_vec.mean())

Mean value is 0.5327205584932704
